server:
  port: 8100

spring:
  appName: turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
  appConfig: mainapp,mainapp2,mainapp3
  clusterNameExpression: "'default'"
